### ISSUE TITLE
Implement search results page

### ISSUE THREAD

**Issue by nyarly** [hackforla/accessthedata-ckan#14]
(not a complete issue description yet)

@mxajPrice - we were noting that the search results page that's integral to CKAN doesn't have a design yet. c.f. https://opendata.swiss/de/dataset?q=  - it's not urgent, because there's plenty for dev to do already, but we will need this design eventually. We might want to hold off until we have CKAN live for designers to reference, or they can work from the UX benchmark sites.

**Comment by nyarly** [comment]
This is dependent on having a design (please reference that issue once it's created)

The design work is  dependent on getting the development site deployed, though.

**Comment by mxajPrice** [comment]
There isn't a design to implement.
