### ISSUE TITLE
Consolidate .gitignore and expand its entries.

### ISSUE THREAD

**Issue by TonyDelgadoWillis** [hackforla/accessthedata-ckan#17]
The are a total of six .gitignore files in this repo. One is in the access-the-data directory. Another four in the hack4laatd extension are completely empty. The one in the root directory is missing some important 

- [x] Combine all .gitignores into the root directory
- [x] Use examples to determine new elements that should be included in the .gitignore.
- [x] Remove files and directories that should be ignored *before* adding the paths to .gitignore.
- [x] Update the root .gitignore.
- [x] Review by Judson

**Comment by mxajPrice** [comment]
@nyarly please review.

**Comment by mxajPrice** [comment]
@nyarly did you have a chance to review this?
