### ISSUE TITLE
Replace home and about page text.

### ISSUE THREAD

**Issue by TonyDelgadoWillis** [hackforla/accessthedata-ckan#24]
The text on the home and about pages reflect a previous iteration of the project. Update them to reflect the text of the most recent designs. More detailed styling to match wireframes will be in future tickets.

See also #6. (we expected to use this method to replace basic text, but it was not possible.)
See also #10 and #11. (More extensive matching of the styling of the about page.)

**Comment by merlinsmagic** [comment]
Hi @TonyDelgadoWillis 

Progress: “What is the current status of your project? What have you completed and what is left to do?”
Blockers: “Difficulties or errors encountered.”
Availability: “How much time will you have this week to work on this issue?”
ETA: “When do you expect this issue to be completed?”
Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by merlinsmagic** [comment]
Reply on Slack from @TonyDelgadoWillis 

I think the test to start the extension clean was pretty clear success, with a functional website closer to wireframes in a shorter amount of time. I made a quick recording of the site running on my machine (though it doesn't show the mouse unfortunately).
I'll write some more in the issues, but things to consider from here are:
How best to handle the repo change (I have this in a personal fork from ckan-docker)
Adding CSS preprocessers (I'm currently just adding to a large CSS file. Faster, but harder to handle for multiple designers)
CKAN has some out-of-the-box features that aren't accounted for in current designs like:
Account header
Breadcrumbs
Site Translation
https://hackforla.slack.com/archives/C01L2ANCG6M/p1691294236782909

**Comment by merlinsmagic** [comment]
Hi @TonyDelgadoWillis ,

Do we have any new updates for this issue?

Progress: “What is the current status of your project? What have you completed and what is left to do?”
Blockers: “Difficulties or errors encountered.”
Availability: “How much time will you have this week to work on this issue?”
ETA: “When do you expect this issue to be completed?”
Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by TonyDelgadoWillis** [comment]
Closed with #28
