### ISSUE TITLE
Update fonts

### ISSUE THREAD

**Issue by nyarly** [hackforla/accessthedata-ckan#5]
- [x] Gather font choices from the design team
- [x] Incorporate those into the CSS

**Comment by merlinsmagic** [comment]
Hi Tony could you give us update on this issue when you have a moment.

Progress: “What is the current status of your project? What have you completed and what is left to do?”
Blockers: “Difficulties or errors encountered.”
Availability: “How much time will you have this week to work on this issue?”
ETA: “When do you expect this issue to be completed?”
Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by TonyDelgadoWillis** [comment]
A Pull Request has been opened to complete this issue. Attached is the most recent view of the site running in a local environment

![image](https://github.com/hackforla/accessthedata-ckan/assets/130938949/0b9da1ef-3824-49be-8eb9-050dd3280d8a)
