### ISSUE TITLE
Update static assets (fonts, svg, image)

### ISSUE THREAD

**Issue by nyarly** [hackforla/accessthedata-ckan#7]
- [x] Collect existing assets from the design team
- [x] Add them to the repository
- [x] Establish a practice for future updates and additions to the assets, so that design understands how to deliver their work

**Comment by merlinsmagic** [comment]
Hi @TonyDelgadoWillis do we have any updates on this issue or new things you would like to share?

Progress: “What is the current status of your project? What have you completed and what is left to do?”
Blockers: “Difficulties or errors encountered.”
Availability: “How much time will you have this week to work on this issue?”
ETA: “When do you expect this issue to be completed?”
Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by merlinsmagic** [comment]
Hi @TonyDelgadoWillis do we have any new updates for this issue or have new things you would like to share?

Progress: “What is the current status of your project? What have you completed and what is left to do?”
Blockers: “Difficulties or errors encountered.”
Availability: “How much time will you have this week to work on this issue?”
ETA: “When do you expect this issue to be completed?”
Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by TonyDelgadoWillis** [comment]
Dev progress: The public folder for images and static files is setup and working locally.

Problems: I'm not certain the files exporting from Figma are the best quality, and I want to see if there is a way to get better quality PNGs. I know we don't currently have a design team, so this will probably involve reaching out to the website team to see bring processes from their workflow.

The layout of some of the images in the cards has been tricky, but technically not in scope for the ticket, so I won't worry about it too much.

**Comment by mxajPrice** [comment]
@TonyDelgadoWillis I reached out to the website team and no bites.  I am trying the UX/UI CoP next.  If I do not get anything from them I'll reach out to the admin team/Bonnie to see what they know.

I created [this issue](https://github.com/hackforla/access-the-data/issues/291) to keep track of this inquiry.

**Comment by mxajPrice** [comment]
[Long story](https://github.com/hackforla/access-the-data/issues/291) short- there are no high-res images.  Let's use the low-res for now and I will note in the MVP close-out report that original art needs to be created to replace what is on the test site.
